# Site settings
title_left    : "علیِ "
title_right   : "هَردان" # default: ""
title         : "علی هردان"
description   : "سایت علی هردان"
description: >- # this means to ignore newlines until "baseurl:"
  سایت علی هردان
#keywords      : "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url           : https://ali0.ir # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
lang: fa_IR

#google_analytics  : UA-XXXXX-XX
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /fa/blog/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Jekyll-seo-tag and 
author:
  twitter: ali_hardan76
  name: علی هردان

twitter:
  username: ali_hardan76
  card: summary

#facebook:
  #app_id: 1234
  #publisher: 1234
  #admins: 1234

logo         : "/assets/images/profile.png"
timezone: "Asia/Tehran"

social:
  name: Ali Hardan
  links:
    - https://twitter.com/ali_hardan76
    - https://github.com/ali-hardan
    - https://stackoverflow.com/users/1552260/ali-hardan

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.png

# End jekyll-seo-tag
#
# _includes/social.html configuration. from `minima` theme.
social_links:
  twitter: ali_hardan76
  github:  ali-hardan
  rss: /fa/feed.xml
  stackoverflow: true
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  telegram: alihardan
  # googleplus: +jekyll
  # microdotblog: jekyll
  #
  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-jalali
  - jekyll-feed
  - jekyll-seo-tag

# navbar pages
#navbar:
  #- slug : about
    #title: درباره
  #- slug : blog
    #title: Blog


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  profile: false
  blanklines: false

feed:
  path: /fa/feed.xml

collections:
  tag:
    output: true
    permalink: /fa/blog/tags/:name/
  category:
    output: true
    permalink: /fa/blog/categories/:name/
  posts:
    output: true
    permalink: /fa/blog/:title/

# set default layout for posts
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
- scope:
    path: _category
    type: category
  values:
    layout: category
- scope:
    path: _tags
    type: tags
  values:
    layout: tag


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
include: ["_redirects"]
